apiVersion: v1
kind: Pod
metadata:
  name: rails.kube8V1.com
  labels:
    app: rails-docker-kube8
spec:
  containers:
  - name: k8s-demo
    image: ramisn/rails-docker-kube8:2.0
    ports:
    - name: rails-port
      containerPort: 3000
